language: node_js
node_js:
- 4
- 6
- 8
env:
  global:
    secure: GstOKLlXZ/7EHQVT9Sml/LbmejoIFstV5y9/icC4KpJ5zf9Z6IA3dwIhao1GnwXatW/6r+olrPjSYdzMU0CxYhhy+/L23fodkHcEVnKJlDh7fq1yodWVPNS31VhtFxSheujYwudX3DJRbTlkWCpeMPdPTj+XMLzd+wK+S7P7hoobH2ioAXC1M2GgFFvRQi+RJNu0jpV5gsEpc1zQY3Hayi7j6CHYsUy6W1SpkQP/8OlJK+LclA0NVfKs7tKfFRtcbJmkGleP2EELlajK10NDA1ecTEbu5p4+RgxbR0lbQFSJNA5UXDfOIuA0FKOSUD3fp3ewk/f1KfneuU9HEEhrjrPoiyP2A5wr3UB2pcaKsyGnQeZBo3gqpFD++ImctTW/2v1Nl7rM25hFaedCTeX58OaWG3aTu9I2dsyhRZ8xDYHH+s3DiLwDmOKfGqWDA18m7ReAnOHWhSh14IHPkfim6t4JNl98IQtUlWaXq2yzNCeaWCZFFA+lL3OaKWaeyuzxnYid3fN/07htjwIuROnGgV8v1nFDCWwcjIV+jOXkrwdlze3s6vaiu2SzXiMU0lqtBCE2+05e6oRHfDROdWXNCdw9OlGJ0yIiaUeesCFhcdna3ZiLEQU5tRynaAriXEtCtLhQofBn1v+SOEu42bTkJGpNg4rYZMmhKZyi51sFS3s=
